site_name: Hashtopolis
site_url: https://docs.hashtopolis.org
repo_url: https://github.com/hashtopolis/server
docs_dir: doc
nav:
 - index.md
 - user_manual/basic_workflow.md
 - Installation Guidelines:
   - installation_guidelines/basic_install.md
   - installation_guidelines/advanced_install.md
   - installation_guidelines/update.md 
   - installation_guidelines/tls.md 
   - installation_guidelines/docker.md
 - User Manual:
   - user_manual/agents.md
   - user_manual/tasks.md
   - user_manual/hashlist.md
   - user_manual/files.md
   - user_manual/crackers_binary.md
   - user_manual/myaccount.md
   - user_manual/settings_and_configuration.md
   - user_manual/users.md
 - FAQ and Tips:
    - faq_tips/faq.md
    - faq_tips/tips.md
 - changelog.md
 - API Reference:
   - APIv2: apiv2.md

theme:
  name: material
  logo: assets/images/logo.png
  features:
   - content.code.copy
   - content.action.edit
edit_uri: blob/docs/doc/ # Edit the URL to the static branch and folder
markdown_extensions:
  - github-callouts # Add the ability of notes, warnings, etc.
  - sane_lists # Make the numbered lists continue
  - attr_list # allows to add HTML attributes and CSS classes
  - md_in_html # allows for writing Markdown inside of HTML