site_name: Hashtopolis
site_url: https://docs.hashtopolis.org
repo_url: https://github.com/hashtopolis/server
docs_dir: doc
nav:
 - index.md
 - install.md
 - user_manual.md
 - advanced.md
 - changelog.md
nav:
 - index.md
 - install.md
 - user_manual.md
 - advanced.md
 - changelog.md
theme:
  name: material
  logo: assets/images/logo.png
edit_uri: blob/docs/doc/ # Edit the URL to the static branch and folder
markdown_extensions:
  - github-callouts # Add the ability of notes, warnings, etc.
  - sane_lists # Make the numbered lists continue