site_name: Hashtopolis
site_url: https://docs.hashtopolis.org
repo_url: https://github.com/hashtopolis/server
docs_dir: doc
nav:
 - index.md
 - Installation Guidelines:
   - installation_guidelines/basic_install.md
   - installation_guidelines/advanced_install.md 
 - User Manual:
   - user_manual/user_manual.md
   - user_manual/advanced_manual.md
   - user_manual/settings_and_configuration.md
 - Advanced Usage:
   - advanced_usage/tls.md
   - advanced_usage/docker.md
   - advanced_usage/generic_cracker.md
   - advanced_usage/slow_hashes.md
 - changelog.md
 - API Reference:
   - APIv2: apiv2.md

theme:
  name: material
  logo: assets/images/logo.png
  features:
   - content.code.copy
   - content.action.edit
edit_uri: blob/docs/doc/ # Edit the URL to the static branch and folder
markdown_extensions:
  - github-callouts # Add the ability of notes, warnings, etc.
  - sane_lists # Make the numbered lists continue
  - attr_list # allows to add HTML attributes and CSS classes
  - md_in_html # allows for writing Markdown inside of HTML