ALTER TABLE AgentStat ALTER COLUMN agentStatId TYPE BIGINT USING id::bigint;
ALTER TABLE Speed ALTER COLUMN speedId TYPE BIGINT USING id::bigint;
ALTER TABLE LogEntry ALTER COLUMN logEntryId TYPE BIGINT USING id::bigint;
