ALTER TABLE AgentStat ALTER COLUMN agentStatId TYPE BIGSERIAL USING agentStatId::bigint;
ALTER TABLE Speed ALTER COLUMN speedId TYPE BIGSERIAL USING speedId::bigint;
ALTER TABLE LogEntry ALTER COLUMN logEntryId TYPE BIGSERIAL USING logEntryId::bigint;
