name: Start Hashtopolis server
description: Starts application containers and waits for Hashtopolis to be ready.

runs:
  using: "composite"
  steps:
    - name: Start application containers
      working-directory: .devcontainer
      run: docker compose up -d
      shell: bash
    - name: Install composer dependencies packages
      run: docker exec hashtopolis-server-dev composer install --working-dir=/var/www/html/
    - name: Wait until entrypoint is finished and Hashtopolis is started
      run: bash .github/scripts/await-hashtopolis-startup.sh
      shell: bash
