name: Start Hashtopolis server
description: Starts application containers and waits for Hashtopolis to be ready.

inputs:
  db_system:
    description: "Used to set which DB system should be used"
    required: true
    default: "mysql"

runs:
  using: "composite"
  steps:
    - name: Start application containers
      working-directory: .devcontainer
      run: docker compose -f docker-compose.${{ github.event.inputs.db_system }}.yml -f
      shell: bash
    - name: Install composer dependencies packages
      run: docker exec hashtopolis-server-dev composer install --working-dir=/var/www/html/
      shell: bash
    - name: Wait until entrypoint is finished and Hashtopolis is started
      run: bash .github/scripts/await-hashtopolis-startup.sh
      shell: bash
