ALTER TABLE AgentStat MODIFY agentStatId BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE Speed MODIFY speedId BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE LogEntry MODIFY logEntryId BIGINT NOT NULL AUTO_INCREMENT;
