name: Generate MkDocs and upload

on:
  push:
    branches:
      - docs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        pip3 install $(mkdocs get-deps)
        sudo apt-get update
        sudo apt-get install -y lftp
        sudo apt-get install nodejs
        sudo apt-get install npm 
        sudo npm i openapi-to-md -g
    - name: Start application containers #same steps as in ci.yml, might make it more modular in the future
      working-directory: .devcontainer
      run: docker compose up -d
    - name: Wait until entrypoint is finished and Hashtopolis is started
      run: bash .github/scripts/await-hashtopolis-startup.sh
    - name: Download newest apiv2 spec
      run: |
        wget http://localhost:8080/api/v2/openapi.json -P /tmp/
        openapi-to-md /tmp/openapi.json /docs/api/
    - name: Build MkDocs site
      run: |
        mkdocs build
    - name: Upload HTML files to FTP server
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -e "mirror -R site/ /; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER
