name: Generate MkDocs and upload

on:
  push:
    branches:
      - docs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        pip install markdown-callouts
        sudo apt-get update
        sudo apt-get install -y lftp

    - name: Build MkDocs site
      run: |
        mkdocs build
    - name: Upload HTML files to FTP server
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -e "mirror -R site/ /; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER
